language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
before-install:
  - "sudo apt-get install suitesparse"
# command to install dependencies
install:
  - "python setup.py install"
# command to run tests
#script: nosetests
