# YAML configuration script

name: default

data:
  grid_name: "CIFIST"
  files: ["data.hdf5"]
  instruments : ["DCT_DeVeny"]

outdir : output/

plotdir : plots/

# The parameters defining your raw spectral library live here.
grid:
  raw_path: "../libraries/raw/CIFIST/"
  hdf5_path: "grid.hdf5"
  parname: ["temp", "logg"]
  key_name: "t{0:.0f}g{1:.1f}" # Specifies how the params are stored
  # in the HDF5 file
  parrange: [[2300, 3700], [4.0, 5.5]]
  wl_range: [6300, 6360]
  buffer: 50. # AA

PCA:
  path : "PCA.hdf5"
  threshold: 0.999 # Percentage of variance explained by components.
  priors: [[2., 0.0075], [2., 0.75], [2., 0.75]] # len(parname) list of 2-element lists. Each 2-element list is [s, r] for the Gamma-function prior on emulator parameters

#Longer strings can be written like this. This will be loaded under the "Comments" variable.
Comments: >
  Mid M dwarfs using emulator.

# The parameters shared between all orders
Theta :
    grid : [2300., 5.0, 0.0]
    vz : 0.0
    vsini : 5.79
    logOmega: -12.80
    Av: 0.0

Theta_jump :
    grid : [3, 0.003, 0.001]
    vz : 0.01
    vsini : 0.01
    logOmega: 1.e-4
    Av: 0.01

cheb_degree: 2
cheb_jump : 1.0e-4

Phi :
    sigAmp : 1.0
    logAmp : -13.6
    l : 20.

Phi_jump :
    sigAmp : 0.025
    logAmp : 0.01
    l : 0.25


chunk_ID: 0
spectrum_ID: 0
instrument_ID: 0
