# YAML configuration script

name: default

data:
  grid_name: "PHOENIX"
  files: ["data/WASP14/WASP14-2009-06-14.hdf5"]
  # data/WASP14/WASP14-2010-03-29.hdf5
  # data/WASP14/WASP14-2010-04-24.hdf5
  instruments : ["TRES"]
  orders: [22]
  #orders: [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36]

outdir : output/

# The parameters defining your raw spectral library live here.
grid:
  raw_path: "libraries/raw/PHOENIX/"
  hdf5_path: "libraries/PHOENIX_TRES_test.hdf5"
  parname: ["temp", "logg", "Z"]
  key_name: "t{0:.0f}g{1:.1f}z{2:.1f}" # Specifies how the params are stored
  # in the HDF5 file
  parrange: [[6000, 6300], [4.0, 5.0], [-1.0, 0.0]]
  wl_range: [5000, 5200]

PCA:
  path : "libraries/PHOENIX_TRES_PCA_test.hdf5"

#Longer strings can be written like this. This will be loaded under the "Comments" variable.
Comments: >
  WASP14 spectrum using emulator.

#Nested data structures are allowed
stellar_params :
    temp : 6420
    #logg : 3.90
    Z : -0.27
    vsini : 4.2
    vz : -4.57
    logOmega: -12.714

fix_logg : 4.29

stellar_jump:
    temp : 2
    #logg : 0.01
    Z : 0.001
    vsini : 0.06
    vz : 0.01
    logOmega: 2.5e-4

use_cov: False
stellar_cov:
    temp_logg : 4.148e-2
    temp_Z : 2.959e-2
    logg_Z : 1.45e-5
    temp_logOmega : 0.
    factor : 0.1

cheb_degree: 4
cheb_jump : 4e-4

no_cov : False

no_region: True

cov_params :
    sigAmp : 1
    logAmp : -14.566
    l : 7.58

cov_jump :
    sigAmp : 0.025
    logAmp : 0.01
    l : 0.25

region_params:
    logAmp: -13.6
    sigma: 7.

region_jump:
    logAmp : 0.13
    mu : 0.002
    sigma : 0.7

region_priors:
    sigma0: 0.5 #AA
    mu_width : 0.03 #AA
    sigma_knee : 10 #km/s
    frac_global : 0.1 #Fraction of the global amplitude lower bound

sigma_clip : 4.

#Burn in time
burn_in : 3000
nuisance_burn : 5000
samples : 50000
