name: StellarSpectra Output #website name
markdown: redcarpet
pygments: true
timezone: America/New_York
encoding: utf-8
website: https://github.com/iancze/StellarSpectra
email: iczekala@cfa.harvard.edu
github: iancze
twitter: iczekala
